device: "cuda"

dataset: 
  type: "lego"
  dir: "/scratch/sravindh/nerf_dataset/lego/"
  half_resolution: True
  is_ndc_required: False # set to True only for forward facing scenes
  use_white_bkgd: False # applies only for blender data

model:
  use_viewdirs: True
  num_pos_encoding_func: 16
  num_dir_encoding_func: 4
  num_coarse_samples_per_ray: 128
  num_fine_samples_per_ray: 128
  include_input_in_posencoding: False
  include_input_in_direncoding: False
  num_selected_rays: 0
  centercrop_epochs: 500

train:
  num_epochs: 1000
  chunk_size: 8192 # set 4096 for 1.2GB of GPU memory
  validate_every: 50
  save_checkpoint_for_every: 100
  lr: 5e-4
  lr_decay: 250
  checkpoint_path: ""

result:
  logdir: ""
  logger: None
   
