device: "cuda"

dataset: 
  type: "lego"
  dir: "/scratch/sravindh/nerf_dataset/lego/"
  half_resolution: True
  is_ndc_required: False # set to True only for forward facing scenes
  use_white_bkgd: False # applies only for blender data

model:
  use_viewdirs: True
  num_pos_encoding_func: 6
  num_dir_encoding_func: 6
  num_coarse_samples_per_ray: 64
  num_fine_samples_per_ray: 128
  include_input_in_posencoding: False
  include_input_in_direncoding: False
  num_selected_rays: 1024
  centercrop_epochs: 500

train:
  num_epochs: 6000
  chunk_size: 32768 # set 4096 for 1.2GB of GPU memory
  validate_every: 500
  save_checkpoint_for_every: 100
  lr: 5e-3
  checkpoint_path: False #'/scratch/sravindh/project_nerf/logs/model_checkpoints/checkpoint190000.tar'
  lr_decay: 250

result:
  logdir: "/scratch/sravindh/project_nerf/logs/"
  logger: None
  is_spherical_rendering: False
   
